# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatacolumns',
            name='column_comment',
            field=models.CharField(default='----', max_length=500),
        ),
        migrations.AlterField(
            model_name='metadatacolumns',
            name='column_default',
            field=models.CharField(default='----', max_length=150),
        ),
        migrations.AlterField(
            model_name='metadatacolumns',
            name='column_key',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='metadatacolumns',
            name='extra',
            field=models.CharField(default='----', max_length=30),
        ),
        migrations.AlterField(
            model_name='metadatacolumns',
            name='is_nullable',
            field=models.CharField(default='---', max_length=3),
        ),
    ]
