# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAPPAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.CharField(max_length=20)),
                ('app_pass', models.CharField(max_length=30)),
                ('app_port', models.SmallIntegerField()),
                ('host', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='model_model.HostInfo')),
            ],
            options={
                'db_table': 'host_app_account',
            },
        ),
    ]
