# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inceptionauditdetail',
            name='err_id',
        ),
        migrations.RemoveField(
            model_name='inceptionauditdetail',
            name='stage_status',
        ),
        migrations.AddField(
            model_name='workordertask',
            name='db_name',
            field=models.CharField(default='test_db', max_length=50),
        ),
        migrations.AlterField(
            model_name='inceptionauditdetail',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
