# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionworkorderinfo',
            name='review_comm',
            field=models.CharField(default='----', max_length=500),
        ),
    ]
