# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionauditdetail',
            name='status_code',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
