# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0002_auto_20170617_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionworkorderinfo',
            name='version',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
