# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0002_auto_20170622_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDataProcedureStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaDataTableStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('table', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='model_model.MetaDataTables', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='metadataprocedure',
            name='content',
        ),
        migrations.AlterField(
            model_name='metadatacolumns',
            name='column_key',
            field=models.CharField(default='---', max_length=3),
        ),
        migrations.AddField(
            model_name='metadataprocedurestructure',
            name='procedure',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='model_model.MetaDataProcedure', unique=True),
        ),
    ]
