# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0002_inceptionworkorderinfo_review_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertask',
            name='work_status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workordertask',
            name='app_port',
            field=models.SmallIntegerField(default=3306),
        ),
        migrations.AlterIndexTogether(
            name='inceptionworkorderinfo',
            index_together=set([('work_user', 'review_status'), ('review_user', 'review_status')]),
        ),
    ]
