# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0003_auto_20170619_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordertask',
            name='wid',
        ),
        migrations.AddField(
            model_name='workordertask',
            name='work_order',
            field=models.OneToOneField(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='model_model.InceptionWorkOrderInfo', to_field='work_order_id'),
            preserve_default=False,
        ),
    ]
