# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0003_auto_20170720_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowquery',
            name='checksum',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='slowquery',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slowqueryhistory',
            name='checksum',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='slowqueryhistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
