# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0003_inceptionworkorderinfo_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionauditdetail',
            name='flag',
            field=models.SmallIntegerField(default=1),
        ),
    ]
