# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0003_auto_20170623_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatatables',
            name='table_comment',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
