# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0004_auto_20170619_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionworkorderinfo',
            name='work_cron_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inceptionworkorderinfo',
            name='work_run_time',
            field=models.DateTimeField(default='1980-01-01 01:01:01'),
        ),
    ]
