# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0004_inceptionauditdetail_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionworkorderinfo',
            name='comm',
            field=models.CharField(default='----', max_length=500),
        ),
        migrations.AlterField(
            model_name='inceptionworkorderinfo',
            name='review_user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='model_model.UserInfo'),
        ),
    ]
