# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0004_auto_20170623_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatacolumns',
            name='column_md5',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
