# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0005_auto_20170618_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionworkorderinfo',
            name='master_host',
            field=models.CharField(default='----', max_length=45),
        ),
    ]
