# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0005_auto_20170619_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceptionworkorderinfo',
            name='work_cron_time',
            field=models.DateTimeField(default='1980-01-01 01:01:01'),
        ),
    ]
