# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0005_metadatacolumns_column_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatacolumns',
            name='column_md5',
            field=models.CharField(max_length=100),
        ),
    ]
