# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0006_auto_20170620_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertask',
            name='audit_status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
