# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0006_auto_20170626_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataindexs',
            name='index_md5',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadatatables',
            name='table_md5',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
