# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0007_auto_20170626_1557'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='metadataprocedurestructure',
            table='mysql_metadata_procedure_structure',
        ),
        migrations.AlterModelTable(
            name='metadatatablestructure',
            table='mysql_metadata_table_structure',
        ),
    ]
