# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0007_auto_20170720_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slowquery',
            name='id',
            field=models.PositiveBigIntegerFieldAuto(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slowqueryhistory',
            name='id',
            field=models.PositiveBigIntegerFieldAuto(primary_key=True, serialize=False),
        ),
    ]
