# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0007_workordertask_audit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordertask',
            name='audit_status',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='workordertask',
            name='work_status',
            field=models.SmallIntegerField(default=10),
        ),
    ]
