# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0008_auto_20170626_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDataDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=50)),
                ('schema_name', models.CharField(max_length=64)),
                ('DEFAULT_CHARACTER_SET_NAME', models.CharField(max_length=32)),
                ('DEFAULT_COLLATION_NAME', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'mysql_metadata_database',
            },
        ),
    ]
