# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0008_auto_20170620_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDataColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_schema', models.CharField(max_length=64)),
                ('table_name', models.CharField(max_length=64)),
                ('column_name', models.CharField(max_length=64)),
                ('column_type', models.CharField(max_length=64)),
                ('collation_name', models.CharField(max_length=32)),
                ('is_nullable', models.CharField(max_length=3)),
                ('column_key', models.CharField(max_length=3)),
                ('column_default', models.CharField(max_length=150)),
                ('extra', models.CharField(max_length=30)),
                ('PRIVILEGES', models.CharField(max_length=80)),
                ('column_comment', models.CharField(max_length=500)),
                ('host', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='model_model.HostInfo')),
            ],
            options={
                'db_table': 'mysql_metadata_columns',
            },
        ),
        migrations.CreateModel(
            name='MetaDataIndexs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_schema', models.CharField(max_length=64)),
                ('table_name', models.CharField(max_length=64)),
                ('column_name', models.CharField(max_length=64)),
                ('non_unique', models.SmallIntegerField()),
                ('index_name', models.CharField(max_length=64)),
                ('seq_in_index', models.SmallIntegerField()),
                ('cardinality', models.BigIntegerField()),
                ('nullable', models.CharField(max_length=3)),
                ('index_type', models.CharField(max_length=16)),
                ('index_comment', models.CharField(max_length=500)),
                ('host', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='model_model.HostInfo')),
            ],
            options={
                'db_table': 'mysql_metadata_indexs',
            },
        ),
        migrations.CreateModel(
            name='MetaDataProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=64)),
                ('routine_name', models.CharField(max_length=64)),
                ('routine_type', models.CharField(max_length=9)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('last_altered', models.DateTimeField()),
                ('host', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='model_model.HostInfo')),
            ],
            options={
                'db_table': 'mysql_metadata_procedure',
            },
        ),
        migrations.CreateModel(
            name='MetaDataTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_schema', models.CharField(max_length=64)),
                ('table_name', models.CharField(max_length=64)),
                ('engine', models.CharField(max_length=64)),
                ('row_format', models.CharField(max_length=10)),
                ('table_rows', models.BigIntegerField()),
                ('avg_row_length', models.BigIntegerField()),
                ('max_data_length', models.BigIntegerField()),
                ('data_length', models.BigIntegerField()),
                ('index_length', models.BigIntegerField()),
                ('data_free', models.BigIntegerField()),
                ('chip_size', models.BigIntegerField()),
                ('auto_increment', models.BigIntegerField(default=0)),
                ('table_collation', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(null=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('check_time', models.DateTimeField(null=True)),
                ('table_comment', models.CharField(max_length=500, null=True)),
                ('host', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='model_model.HostInfo')),
            ],
            options={
                'db_table': 'mysql_metadata_tables',
            },
        ),
        migrations.AlterUniqueTogether(
            name='metadatatables',
            unique_together=set([('table_name', 'table_schema', 'host')]),
        ),
        migrations.AlterIndexTogether(
            name='metadataprocedure',
            index_together=set([('routine_name', 'schema_name', 'host')]),
        ),
        migrations.AlterIndexTogether(
            name='metadataindexs',
            index_together=set([('table_name', 'table_schema', 'host')]),
        ),
        migrations.AlterIndexTogether(
            name='metadatacolumns',
            index_together=set([('table_name', 'table_schema', 'host')]),
        ),
    ]
