# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0009_metadatadatabase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadatadatabase',
            old_name='DEFAULT_CHARACTER_SET_NAME',
            new_name='default_character_set_name',
        ),
        migrations.RenameField(
            model_name='metadatadatabase',
            old_name='DEFAULT_COLLATION_NAME',
            new_name='default_collation_name',
        ),
        migrations.AddField(
            model_name='metadatadatabase',
            name='db_md5',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
