# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0010_getmetadataerror'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='getmetadataerror',
            table='get_metadata_error',
        ),
    ]
