# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_model', '0011_auto_20170720_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slowquery',
            old_name='id',
            new_name='aid',
        ),
    ]
